### ISSUE TITLE
Probabkly a stupid question but .....

### ISSUE THREAD

**Issue by ghost** [ReshyResh/BTC-Lottery#1]
dont we have to worry about Rate Limit System ??

Shit is hella fast and im just running it in background i just wann make sure if there is a rate limit that could affect/alter results if person isnt watching the screen as it goes on doing its business  

Also Great Job man !! i caught it the first hour or so after you made it and its still going strong ! also  thanks for taking the time and making it so false positives are almost impossible ! your actually making it so the user has everything they will need if they finally hit the lottery im to broke and cheap to play the real one :0 this is free ! i actaully enjoy just watching the data scrolling through ! makes me look like a hacker when Friends come in so much data so fast they will never know the difference :D

**Comment by ghost** [comment]
sorry idk how to make it not an "Issue" But a "question" instead so please forgive me for that

**Comment by ReshyResh** [comment]
Hello, I'm not really sure I get the question correctly. You're afraid of results coming in so fast that it won't detect a wallet with transactions on it? 
I don't really think that's going to happen, I made a new file called `BTC_Lottery_Single_Page` where you can insert a number of page of your choice to scan for the addresses, so you can test with a working address and have proof that the script works. 

(Try 412146261462724578030299224086806743063916127103968361179779786746970751006 for example).

**Comment by ghost** [comment]
well with  rate limit system if you excced it it can lead to an IP ban but the new API your using may not have it enforced because i have had ip ban from Blockchain API Before but luckily wasnt on my actual  ip
